"use client"

import { useState } from "react"
import { motion, AnimatePresence } from "framer-motion"
import {
  Zap, Loader2, BookOpen, Clock, CheckCircle2,
  FileText, RotateCcw, Copy, Check
} from "lucide-react"
import { cn } from "@/lib/utils"
import { COURSES, LESSON_PLANS } from "@/lib/demo-data"

const GENERATED_PLAN = `# Lesson Plan: Introduction to Recursion
Course: CS 1010 — Introduction to Programming
Standard: CS-ALG-3.2  ·  Duration: 75 min  ·  Dr. Marcus Webb

──────────────────────────────────────────────

LEARNING OBJECTIVES
By the end of this lesson, students will be able to:
1. Define recursion and identify base cases vs recursive cases
2. Trace the execution of a recursive function step-by-step
3. Implement factorial, fibonacci, and array_sum recursively
4. Explain why a missing base case causes a stack overflow

──────────────────────────────────────────────

LESSON STRUCTURE

[15 min] Warm-Up — Russian Nesting Dolls Analogy
  Open with a physical metaphor: nesting dolls inside nesting dolls.
  Question: "How do you know when to stop opening?" → Base case
  Think-pair-share: identify base/recursive cases in everyday life.

[25 min] Concepts & Live Coding
  Factorial — classic intro:

    def factorial(n):
        if n == 0:        # Base case
            return 1
        return n * factorial(n - 1)   # Recursive case

  Draw the call stack on the board for factorial(4).
  Live demo: remove the base case → RecursionError → discuss stack overflow.

[20 min] Pair Programming Exercise
  Students implement fibonacci(n) and array_sum(lst) recursively.
  Circulate — prompt struggling pairs: "What is the smallest version
  of this problem you can solve directly?"

[15 min] Exit Ticket & Wrap-Up
  3 auto-graded MCQs on Canvas.
  Spaced repetition preview: "Next class we apply this to binary search."

──────────────────────────────────────────────

STANDARDS ALIGNMENT
  CS-ALG-3.2: Algorithm design including recursion  ✓
  ACCS Computational Thinking Strand 4               ✓
  SACSCOC Learning Outcome: Critical Thinking        ✓

──────────────────────────────────────────────

DIFFERENTIATION
  Advanced  → Add memoization to fibonacci; compare O(2^n) vs O(n)
  Struggling → Provide annotated starter code with strategic blanks

──────────────────────────────────────────────

MATERIALS
  - VS Code + Python 3.10 (lab computers)
  - Whiteboard for call-stack diagrams
  - Pair programming worksheet (Appendix A)

──────────────────────────────────────────────
Generated by SERA Teacher Assistant Agent
Review before publishing · Does NOT make final grade decisions`

export default function TeacherCurriculumPage() {
  const [topic, setTopic] = useState("")
  const [courseId, setCourseId] = useState("cs101")
  const [duration, setDuration] = useState("75")
  const [isGenerating, setIsGenerating] = useState(false)
  const [generated, setGenerated] = useState("")
  const [streamComplete, setStreamComplete] = useState(false)
  const [copied, setCopied] = useState(false)

  const handleGenerate = () => {
    if (!topic.trim() || isGenerating) return
    setGenerated("")
    setStreamComplete(false)
    setIsGenerating(true)

    let i = 0
    const interval = setInterval(() => {
      i += 6
      setGenerated(GENERATED_PLAN.slice(0, i))
      if (i >= GENERATED_PLAN.length) {
        clearInterval(interval)
        setGenerated(GENERATED_PLAN)
        setIsGenerating(false)
        setStreamComplete(true)
      }
    }, 12)
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(generated)
    setCopied(true)
    setTimeout(() => setCopied(false), 1500)
  }

  return (
    <div className="space-y-6 animate-fade-up">
      <div>
        <h1 className="page-title">AI Lesson Generator</h1>
        <p className="mt-1 text-sm text-[#52525B]">Standards-aligned lesson plans in seconds</p>
      </div>

      <div className="grid gap-6 lg:grid-cols-5">
        {/* Form panel */}
        <div className="lg:col-span-2 space-y-4">
          <div className="rounded-xl border border-[#E8E6E1] bg-white p-5">
            <div className="flex items-center gap-2 mb-4">
              <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-[#FEF9C3]">
                <Zap className="h-3.5 w-3.5 text-[#B8860B]" />
              </div>
              <p className="text-sm font-semibold text-[#18181B]">Generate Plan</p>
            </div>

            <div className="space-y-3.5">
              <div>
                <label className="mb-1.5 block text-xs font-medium text-[#18181B]">
                  Topic <span className="text-[#DC2626]">*</span>
                </label>
                <input
                  type="text"
                  value={topic}
                  onChange={(e) => setTopic(e.target.value)}
                  placeholder="e.g. Introduction to Recursion"
                  className="h-10 w-full rounded-lg border border-[#E8E6E1] bg-white px-3 text-sm outline-none transition-colors focus:border-[#4F46E5] focus:ring-2 focus:ring-[#4F46E5]/10"
                />
              </div>

              <div>
                <label className="mb-1.5 block text-xs font-medium text-[#18181B]">Course</label>
                <select
                  value={courseId}
                  onChange={(e) => setCourseId(e.target.value)}
                  className="h-10 w-full rounded-lg border border-[#E8E6E1] bg-white px-3 text-sm outline-none focus:border-[#4F46E5]"
                >
                  {COURSES.map((c) => (
                    <option key={c.id} value={c.id}>{c.code} — {c.title}</option>
                  ))}
                </select>
              </div>

              <div>
                <label className="mb-1.5 block text-xs font-medium text-[#18181B]">Duration</label>
                <select
                  value={duration}
                  onChange={(e) => setDuration(e.target.value)}
                  className="h-10 w-full rounded-lg border border-[#E8E6E1] bg-white px-3 text-sm outline-none focus:border-[#4F46E5]"
                >
                  <option value="50">50 minutes</option>
                  <option value="75">75 minutes</option>
                  <option value="90">90 minutes</option>
                  <option value="120">2 hours (lab)</option>
                </select>
              </div>

              <button
                onClick={handleGenerate}
                disabled={!topic.trim() || isGenerating}
                className="flex h-10 w-full items-center justify-center gap-2 rounded-lg bg-[#4F46E5] text-sm font-medium text-white transition-colors hover:bg-[#4338CA] disabled:opacity-50"
              >
                {isGenerating
                  ? <><Loader2 className="h-4 w-4 animate-spin" /> Generating…</>
                  : <><Zap className="h-4 w-4" /> Generate Lesson Plan</>
                }
              </button>
            </div>
          </div>

          {/* Saved plans */}
          <div className="rounded-xl border border-[#E8E6E1] bg-white">
            <div className="border-b border-[#E8E6E1] px-4 py-3.5">
              <p className="text-sm font-semibold text-[#18181B]">Saved Plans</p>
            </div>
            <div className="divide-y divide-[#F4F4F2]">
              {LESSON_PLANS.map((plan) => (
                <button
                  key={plan.id}
                  onClick={() => setTopic(plan.title)}
                  className="flex w-full items-start gap-3 px-4 py-3 text-left transition-colors hover:bg-[#FAFAF9]"
                >
                  <div className={cn(
                    "mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full",
                    plan.status === "published" ? "bg-[#D1FAE5]" : "bg-[#FEF3C7]"
                  )}>
                    {plan.status === "published"
                      ? <CheckCircle2 className="h-3 w-3 text-[#059669]" />
                      : <Clock className="h-3 w-3 text-[#D97706]" />}
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="truncate text-sm font-medium text-[#18181B]">{plan.title}</p>
                    <p className="text-[11px] text-[#A1A1AA]">{plan.course} · {plan.duration}min · {plan.generatedAt}</p>
                  </div>
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* Output panel */}
        <div className="lg:col-span-3">
          <div className="flex h-full flex-col rounded-xl border border-[#E8E6E1] bg-white" style={{ minHeight: 540 }}>
            <div className="flex items-center justify-between border-b border-[#E8E6E1] px-5 py-3.5">
              <div className="flex items-center gap-2">
                <FileText className="h-4 w-4 text-[#52525B]" />
                <p className="text-sm font-semibold text-[#18181B]">
                  {generated ? (topic || "Generated Plan") : "Output"}
                </p>
                {isGenerating && (
                  <div className="flex items-center gap-1.5 rounded-full bg-[#EEF2FF] px-2 py-0.5">
                    <Loader2 className="h-3 w-3 animate-spin text-[#4F46E5]" />
                    <span className="text-[10px] font-medium text-[#4F46E5]">Writing…</span>
                  </div>
                )}
                {streamComplete && (
                  <span className="flex items-center gap-1 rounded-full bg-[#D1FAE5] px-2 py-0.5 text-[10px] font-semibold text-[#059669]">
                    <CheckCircle2 className="h-3 w-3" /> Ready
                  </span>
                )}
              </div>
              {generated && (
                <div className="flex items-center gap-1.5">
                  <button onClick={handleCopy} className="flex items-center gap-1.5 rounded-lg border border-[#E8E6E1] px-2.5 py-1.5 text-xs text-[#52525B] hover:border-[#D6D3CC]">
                    {copied ? <Check className="h-3.5 w-3.5 text-[#059669]" /> : <Copy className="h-3.5 w-3.5" />}
                    {copied ? "Copied" : "Copy"}
                  </button>
                  <button
                    onClick={() => { setGenerated(""); setStreamComplete(false) }}
                    className="flex items-center gap-1.5 rounded-lg border border-[#E8E6E1] px-2.5 py-1.5 text-xs text-[#52525B] hover:border-[#D6D3CC]"
                  >
                    <RotateCcw className="h-3.5 w-3.5" /> Clear
                  </button>
                  {streamComplete && (
                    <button className="flex items-center gap-1.5 rounded-lg bg-[#059669] px-2.5 py-1.5 text-xs font-medium text-white hover:bg-[#047857]">
                      <CheckCircle2 className="h-3.5 w-3.5" /> Publish
                    </button>
                  )}
                </div>
              )}
            </div>

            <div className="flex-1 overflow-y-auto p-5">
              <AnimatePresence mode="wait">
                {!generated ? (
                  <motion.div
                    key="empty"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    className="flex h-full flex-col items-center justify-center gap-4 py-16 text-center"
                  >
                    <div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[#FEF9C3]">
                      <Zap className="h-7 w-7 text-[#B8860B]" />
                    </div>
                    <div>
                      <p className="text-sm font-medium text-[#18181B]">No plan generated yet</p>
                      <p className="mt-1 text-xs text-[#A1A1AA]">
                        Enter a topic and click Generate to create a<br />
                        standards-aligned lesson plan in seconds
                      </p>
                    </div>
                    <div className="flex flex-wrap justify-center gap-2">
                      {["Recursion", "Binary Trees", "Integration by Parts", "Clinical Documentation"].map((s) => (
                        <button
                          key={s}
                          onClick={() => setTopic(s)}
                          className="rounded-full border border-[#E8E6E1] px-3 py-1 text-xs text-[#52525B] transition-colors hover:border-[#4F46E5] hover:text-[#4F46E5]"
                        >
                          {s}
                        </button>
                      ))}
                    </div>
                  </motion.div>
                ) : (
                  <motion.pre
                    key="content"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    className="whitespace-pre-wrap font-mono text-xs leading-relaxed text-[#18181B]"
                  >
                    {generated}
                    {isGenerating && (
                      <motion.span
                        animate={{ opacity: [1, 0] }}
                        transition={{ duration: 0.5, repeat: Infinity }}
                        className="ml-0.5 inline-block h-3.5 w-0.5 bg-[#4F46E5] align-middle"
                      />
                    )}
                  </motion.pre>
                )}
              </AnimatePresence>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
